### ISSUE TITLE
Create document repository for Sub-WG members

### ISSUE THREAD

**Issue by ChristineP2024** [PHACDataHub/irg#26]
Members of the Sub-WG external to PHAC/HC do not have access to Sharepoint. This being the case, we need to create a document repository in GitHub, where everyone will have access. 

Repo to contain: 
- Sub-WG meeting documentation (agenda, deck, minutes)
- Question and Answer Document

```[tasklist]
### Tasks
- [x] Create repository
- [x] Share link with product team
- [x] Add documents
```

**Comment by samiatoui** [comment]
Pending team's feedback regarding whether to use the WIKI feature or a new repo.
